CONFIG_MULTITHREADING=y
CONFIG_MAIN_STACK_SIZE=8192

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_THREAD_NAME=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y

CONFIG_NETWORKING=y
CONFIG_WIFI=y

CONFIG_ESPNOW_ROLE_BIDIR=y
CONFIG_ESPNOW_CHANNEL=6
CONFIG_ESPNOW_BEACON_INTERVAL_S=2

